### ISSUE TITLE
ImportError: /home/nkjx/dextairity/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by canhe173** [columbia-ai-robotics/dextairity#2]
When I run **python test_sim.py** following the **readme.md**, I get the following error:

`Traceback (most recent call last): File "test_sim.py", line 2, in <module> from sim_env import SimEnv File "/home/hc/dextairity/sim_env.py", line 7, in <module> import pyflex ImportError: /home/hc/dextairity/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument`

Someone thinks that the CUDA environment currently running is different from the environment in which the code is compiled. However, this is not an effective solution to the problem I encountered.

`**nvcc -V**:
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

**echo $CUDA_HOME**:
/usr/local/cuda-11.3
`
My environment:
- OS: [Ubuntu 18.04]
- PyTorch version [1.10.2]
- torchvision version [0.11.3]
- CUDA and CUDNN version 11.3, 8.4.1
- nvidia driven version [515.65.01]
- GPU model [GeForce RTX 3060]

**Comment by zhenjia-xu** [comment]
Thanks for your interest.
Are you using docker for the compilation of pyflex and importing pyflex outside the docker container?
If so, I remember there may be a potential permission issue since the file created inside the docker can not be read outside. The easiest way is to change the file permission inside the docker, for example `chmode -R 777 PyFlex`
BTW, just double-check if you are using the same dockerfile and conda env as mentioned in this repo?

**Comment by canhe173** [comment]
> Thanks for your interest. Are you using docker for the compilation of pyflex and importing pyflex outside the docker container? If so, I remember there may be a potential permission issue since the file created inside the docker can not be read outside. The easiest way is to change the file permission inside the docker, for example `chmode -R 777 PyFlex` BTW, just double-check if you are using the same dockerfile and conda env as mentioned in this repo?

Thanks for your reply, I tried to modify the permission of PyFlex as you said, but the error was not solved. My modification to CUDA env as mentioned in this repo is only to change **cudatoolkit from 11.1 to 11.3**. Meanwhile, I made the following change to the dockerfile.
`
FROM nvidia/cuda:9.2-devel-ubuntu18.04 ------------------->
FROM nvidia/cuda:11.3.1-devel-ubuntu18.04`

**Comment by zhenjia-xu** [comment]
Flex compilation only supports CUDA 9.2. Therefore, please keep `nvidia/cuda:9.2-devel-ubuntu18.04`.
After compilation, you can use `pyflex` using other CUDA version (e.g., CUDA 11) outside the docker env

**Comment by canhe173** [comment]
> Flex compilation only supports CUDA 9.2. Therefore, please keep `nvidia/cuda:9.2-devel-ubuntu18.04`. After compilation, you can use `pyflex` using other CUDA version (e.g., CUDA 11) outside the docker env

Thanks for your effective reply, I have solved that problem. However, I encountered two new problems:
**The first question：**I run the command:
`python test_cloth_unfolding.py \
  --grasp_checkpoint pretrained_models/DextAIRity_grasp.pth \
  --blow_checkpoint pretrained_models/DextAIRity_blow.pth \
  --task TASK`
The following **error** occurred：
`Traceback (most recent call last):
  File "test_cloth_unfolding.py", line 219, in <module>
    main(args)
  File "test_cloth_unfolding.py", line 60, in main
    checkpoint = torch.load(args.grasp_checkpoint, map_location=grasp_device)
  File "/home/nkjx/miniconda3/envs/DextOrigin/lib/python3.6/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/nkjx/miniconda3/envs/DextOrigin/lib/python3.6/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted
`
Some people think that the reason for this error is that when training the model, the version of pytorch is not consistent with the current version of pytorch, which is not very compatible. But I follow the conda virtual environment installed by readme.md, and the pytorch version is 1.10.2.

**The second question:** I run the command without any code changes:
`# grasping policy pre-training
python train_cloth_unfolding.py \
  --policy DextAIRity_fixed`
The following **error** occurred：
`Traceback (most recent call last):
  File "train_cloth_unfolding.py", line 1041, in <module>
    main(args)
  File "train_cloth_unfolding.py", line 750, in main
    envs = [RaySimEnv.remote(gui=False, wind_life_time=args.wind_life_time, large_grasp=False, pick_and_place=args.grasp_policy == 'pick_and_place') for _ in range(args.env_num)]
  File "train_cloth_unfolding.py", line 750, in <listcomp>
    envs = [RaySimEnv.remote(gui=False, wind_life_time=args.wind_life_time, large_grasp=False, pick_and_place=args.grasp_policy == 'pick_and_place') for _ in range(args.env_num)]
  File "/home/nkjx/miniconda3/envs/DextOrigin/lib/python3.6/site-packages/ray/actor.py", line 637, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/home/nkjx/miniconda3/envs/DextOrigin/lib/python3.6/site-packages/ray/util/tracing/tracing_helper.py", line 387, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/nkjx/miniconda3/envs/DextOrigin/lib/python3.6/site-packages/ray/actor.py", line 884, in _remote
    creation_args = signature.flatten_args(function_signature, args, kwargs)
  File "/home/nkjx/miniconda3/envs/DextOrigin/lib/python3.6/site-packages/ray/_private/signature.py", line 114, in flatten_args
    raise TypeError(str(exc)) from None
TypeError: got an unexpected keyword argument 'pick_and_place'
`

**Comment by Rudy112** [comment]
Hi @zhenjia-xu , GREAT WORK, and thanks for sharing the code. I also have the same problem as above.  However, the image for `nvidia/cuda:9.2-devel-ubuntu18.04` is no longer available for download. Is there any way we can get the image? 

THANKS SO MUCH FOR YOUR HELP!
